Fix 'Outbound federation will ignore a missing event with bad JSON for room version 6'
matrix-org/sytest pull request #1061
Opened 2021-07-01 09:54 UTC by erikjohnston

c.f. https://github.com/matrix-org/synapse/issues/10275

2021-07-01 10:05 UTC, richvdh requested changes

2021-07-01 10:05 UTC, richvdh commented on tests/50federation/33room-get-missing-events.pl
> +# * To check this we send some another valid event pointing at the "good" event,
```suggestion
# * To check this we send another valid event pointing at the "good" event,
```

2021-07-01 10:05 UTC, richvdh commented on tests/50federation/33room-get-missing-events.pl
> +               Future->done;
if this is a cut and paste of the earlier code, let's factor it out to a separate `sub` ?

2021-07-01 10:48 UTC, richvdh commented
do we even still need this test, given it has been ported to complement?

2021-07-02 14:07 UTC, erikjohnston commented
> do we even still need this test, given it has been ported to complement?

FTR we decided we *do* want to keep the test here, at least until we can add worker mode to complement and add it to CI

2021-07-07 11:26 UTC, richvdh approved these changes
looks generally plausible, modulo CI being borked

2021-07-07 14:57 UTC, merged