Attempt to deflake `The only membership state included in an initial …
matrix-org/sytest pull request #1145
Opened 2021-09-20 15:49 UTC by DMRobertson

…sync is for all the senders in the timeline`

Hopefully fixes #1050

2021-09-21 12:40 UTC, anoadragon453 requested changes
Looks sensible, just a couple clarifying comments.

Failing tests in Dendrite are unrelated.

2021-09-21 12:40 UTC, anoadragon453 commented on tests/31sync/15lazy-members.pl
> +         # Ensure synapse has propagated this message to Alice's synchotron
```suggestion
         # Ensure synapse has propagated this message to Alice's sync stream
```

"synchrotron" is a bit of an unofficial name that we mostly just use to describe sync workers on Synapse.

2021-09-21 12:40 UTC, anoadragon453 commented on tests/31sync/15lazy-members.pl
> +            $result
Is this the equivalent of `return $result;`, similar to rust?

2021-09-22 11:27 UTC, anoadragon453 commented on tests/31sync/15lazy-members.pl
> +            $result
Aha, OK. Thanks for the explanation. Also looks like there is no differentiator through the semicolon as I originally thought.

2021-09-22 11:28 UTC, anoadragon453 approved these changes

2021-09-22 13:14 UTC, merged

2021-09-22 13:16 UTC, richvdh commented on tests/10apidoc/09synced.pl
> +      or die "Expected only ".(scalar @{ $member_ids })." membership events (got ".(scalar @members).")";
for future reference, it's generally easier to replace this sort of construction with a call to `assert_eq`. (`assert_*` didn't exist very early in sytest's history, so this sort of `foo == bar or die` construction typically predates its existence)