Use the `dendrite` branch by default for Dendrite
matrix-org/sytest pull request #1237
Opened 2022-04-06 11:03 UTC by neilalexander

That way we can choose when to merge the latest `develop` changes into our branch rather than find CI turns into a sea of red randomly.

2022-04-06 11:30 UTC, squahtx approved these changes
lgtm!

2022-06-17 08:27 UTC, richvdh requested changes

2022-06-17 08:27 UTC, richvdh commented on docker/dendrite.Dockerfile
> +ENV SYTEST_DEFAULT_BRANCH dendrite
a comment here would be good. What does this do, and why is it useful? (I shouldn't have to go digging around in a bunch of other files to figure it out)

2022-11-30 13:02 UTC, S7evinK commented
I've added a comment about the ENV and removed building `sytest-dendrite` on pull to `develop`. We're going to build the image on-demand from the `dendrite` branch later on.

2022-11-30 13:48 UTC, kegsay approved these changes

2022-11-30 13:59 UTC, merged